config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('contact', include('contact.urls')),
]

contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact'

urlpatterns = [
    path('', views.ContactView.as_view(), name='contact'),
    ]

home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    ]

contact/models.py
from django.db import models

# Create your models here.

contact/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class ContactView(TemplateView):
    template_name = 'contact/contact.html'

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home/index.html'

contact/templates/contact/contact.html
{% extends 'base.html' %}


{% block title %}Contact{% endblock %}

{% block container %}
<h1>Contact View</h1>
{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}
{% block container %}
<h1>Home View</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae, deleniti dolores dolorum error fugiat hic illum inventore laboriosam natus numquam officiis placeat quasi soluta temporibus vitae? Commodi culpa cum dicta esse eveniet explicabo fugit harum impedit in ipsam itaque labore, laborum laudantium minima praesentium quaerat rem rerum tempore vel voluptatibus! At debitis dignissimos distinctio, dolorum exercitationem fuga ipsam, ipsum laudantium necessitatibus quaerat quidem recusandae sunt. Aperiam atque aut consequatur distinctio eaque eius eos incidunt ipsam nobis non nostrum pariatur porro repudiandae tempore temporibus, ullam, voluptatibus! Alias aliquid asperiores cumque dignissimos dolorem explicabo facilis hic id natus qui? Adipisci amet architecto aspernatur assumenda, autem beatae consequuntur culpa cum dolorem doloremque in, ipsam magni maiores maxime minima minus modi molestiae mollitia nesciunt nihil nobis numquam perspiciatis, placeat possimus sequi tempora velit! Ad alias aperiam architecto consectetur cum cumque debitis dolor eaque eius expedita fugiat illum iste laboriosam libero molestias necessitatibus, nesciunt non numquam placeat quaerat quia quis saepe soluta tempore velit veritatis vitae voluptatum? Animi beatae commodi dolorum eius explicabo inventore ipsa iste, iusto laborum maxime minus nam necessitatibus nulla placeat quae quas qui ratione sunt totam ullam! Accusantium amet architecto harum ipsa itaque labore, obcaecati odio, quae rem, unde vel veritatis.</p>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'scripts/app.js' %}" async defer></script>
{% endblock %}

{% block aside %}
<!--    {{ block.super }}-->
<!--    {{ block.super }}-->
    <h2>Aside</h2>
<!--    {{ block.super }}-->
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Coffee shop - {% block title %}{% endblock %}</title>
<!--    podpiecie cssa od bootstrapa-->
    {% block styles %}
        <link rel="stylesheet" href="{% static 'styles/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    {% endblock %}
<!--    podpiecie js od bootstrapa-->
    {% block scripts %}
        <script src="{% static 'scripts/bootstrap.min.js' %}" async defer></script>
    {% endblock %}
</head>

<body>

{% include 'partials/_header.html' %}

<main class="container mt-3">
    <div class="row">
        <section class="col-sm-12 cold-md-8 col-lg-6">
            {% block container %}

            {% endblock %}
        </section>

        <aside class="col-sm-12 cold-md-4 col-lg-6">
            {% block aside %}

                <h2>Jestem asidem z base'a</h2>
            {% endblock %}
        </aside>

    </div>
    <div class="row">
        <div class="col-sm-4 offset-8 col-md-2 offset-md-10">
            {% include 'partials/_footer.html' %}
        </div>
    </div>
</main>



<h1>Jestem z base'a</h1>




</body>
</html>

templates/partials/_footer.html
<footer>
    <p class="text-lg">&copy; Copyright</p>
</footer>

templates/partials/_header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home:home' %}">

      <img class="logo" src="{% static 'images/logo.svg' %}" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'contact:contact' %}">Contact</a>
        </li>

      </ul>
    </div>
  </div>
</nav>